# Generated by Django 5.1 on 2024-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(null=True, upload_to='measurement/images/', verbose_name='Изображение'),
        ),
    ]
